const copy = {
  es: {
    nav:['Inicio','Lugares','Alojamiento','RSVP'], skip:'Ir al contenido', footer:'Roma, con vosotros.', marry:'¡Nos casamos!', date:'3 de julio de 2027', city:'Roma, Italia', intro:'Una ciudad especial. Nuestra gente favorita. Nos encantará compartir este día con vosotros.', discover:'Descubre los lugares', photo:'JUNTOS, HACIA LO QUE VIENE', ceremony:'La ceremonia', reception:'La celebración', weekend:'Vuestra estancia', stayShort:'Unos días en Roma para celebrar juntos.', more:'Ver detalles', hotels:'Ver alojamiento', locationsTitle:'Dos lugares, un gran día', locationsIntro:'Del «sí, quiero» a la última canción. Aquí nos encontraremos para celebrarlo juntos.', churchText:'La ceremonia tendrá lugar en Sant’Anselmo, en el Aventino, Roma.', villaText:'Después de la ceremonia, seguiremos celebrando en Villa Demetra.', maps:'Abrir en Google Maps ↗', timing:'Horarios y detalles de transporte próximamente.', stayTitle:'Unos días en Roma', stayIntro:'Todo lo necesario para organizar vuestra estancia, en un mismo lugar.', soon:'Próximamente', stayHeading:'Un lugar para descansar', stayText:'Estamos preparando una selección de hoteles y alojamientos. Aquí compartiremos las opciones, los enlaces de reserva y las posibles tarifas para invitados.', stayAside:'¿Todavía no habéis reservado?', stayAdvice:'No pasa nada. Cuando abramos las confirmaciones, podréis indicar «Aún no lo sé» y añadir vuestro alojamiento más adelante.', stayLocation:'La ceremonia será en el Aventino y la celebración en Villa Demetra. Tened en cuenta ambos lugares al planificar vuestra estancia.', rsvpTitle:'¿Celebramos juntos?', rsvpIntro:'Nos hará mucha ilusión teneros a nuestro lado.', closed:'Las confirmaciones todavía no están abiertas. Compartiremos aquí los detalles cuando esté todo listo.', how:'Así podréis confirmar', steps:[['Vuestra invitación','Acceded con vuestro enlace o código privado.'],['Vuestros planes','Indicad quién viene y compartid los detalles de vuestra estancia.'],['Siempre al día','Volved con el mismo enlace para consultar o modificar vuestra respuesta.']], questions:'¿Qué os preguntaremos?', fields:['Quién asistirá de vuestra invitación','Necesidades alimentarias y alergias de cada persona','Alojamiento, aunque todavía no esté reservado','Necesidades de transporte, si lo organizamos'], planned:'Las preguntas definitivas se compartirán cuando abramos las confirmaciones.'
  },
  it: {
    nav:['Home','Luoghi','Alloggi','RSVP'],skip:'Vai al contenuto',footer:'Roma, insieme a voi.',marry:'Ci sposiamo!',date:'3 luglio 2027',city:'Roma, Italia',intro:'Una città speciale. Le nostre persone preferite. Non vediamo l’ora di condividere questa giornata con voi.',discover:'Scoprite i luoghi',photo:'INSIEME, VERSO QUELLO CHE VERRÀ',ceremony:'La cerimonia',reception:'Il ricevimento',weekend:'Il vostro soggiorno',stayShort:'Qualche giorno a Roma per festeggiare insieme.',more:'Scopri i dettagli',hotels:'Scopri gli alloggi',locationsTitle:'Due luoghi, un giorno speciale',locationsIntro:'Dal «sì, lo voglio» all’ultima canzone. Ecco dove ci ritroveremo per festeggiare insieme.',churchText:'La cerimonia si terrà a Sant’Anselmo, sull’Aventino, a Roma.',villaText:'Dopo la cerimonia, continueremo i festeggiamenti a Villa Demetra.',maps:'Apri in Google Maps ↗',timing:'Orari e informazioni sui trasporti saranno disponibili prossimamente.',stayTitle:'Qualche giorno a Roma',stayIntro:'Tutte le informazioni per organizzare il vostro soggiorno, in un unico posto.',soon:'Prossimamente',stayHeading:'Un posto dove riposare',stayText:'Stiamo preparando una selezione di hotel e alloggi. Qui condivideremo le opzioni, i link per prenotare ed eventuali tariffe riservate agli invitati.',stayAside:'Non avete ancora prenotato?',stayAdvice:'Nessun problema. Quando apriremo le conferme, potrete indicare «Non lo so ancora» e aggiungere il vostro alloggio in seguito.',stayLocation:'La cerimonia sarà sull’Aventino e il ricevimento a Villa Demetra. Tenete conto di entrambi i luoghi quando organizzate il soggiorno.',rsvpTitle:'Festeggiamo insieme?',rsvpIntro:'Saremo felicissimi di avervi al nostro fianco.',closed:'Le conferme non sono ancora aperte. Condivideremo qui i dettagli quando sarà tutto pronto.',how:'Come potrete confermare',steps:[['Il vostro invito','Accedete con il vostro link o codice privato.'],['I vostri programmi','Indicate chi parteciperà e condividete i dettagli del soggiorno.'],['Sempre aggiornati','Tornate con lo stesso link per consultare o modificare la risposta.']],questions:'Cosa vi chiederemo?',fields:['Chi parteciperà tra le persone invitate','Esigenze alimentari e allergie di ogni persona','Alloggio, anche se non ancora prenotato','Necessità di trasporto, se lo organizzeremo'],planned:'Le domande definitive saranno disponibili all’apertura delle conferme.'
  },
  en: {
    nav:['Home','Locations','Accommodation','RSVP'],skip:'Skip to content',footer:'Rome, together with you.',marry:'We’re getting married!',date:'3 July 2027',city:'Rome, Italy',intro:'A special city. Our favourite people. We can’t wait to share this day with you.',discover:'Explore the locations',photo:'TOGETHER, FOR ALL THAT COMES NEXT',ceremony:'The ceremony',reception:'The celebration',weekend:'Your stay',stayShort:'A few days in Rome to celebrate together.',more:'View details',hotels:'Explore accommodation',locationsTitle:'Two places, one special day',locationsIntro:'From “I do” to the last song. Here’s where we’ll come together to celebrate.',churchText:'Our ceremony will take place at Sant’Anselmo, on Rome’s Aventine Hill.',villaText:'After the ceremony, we’ll continue the celebrations at Villa Demetra.',maps:'Open in Google Maps ↗',timing:'Timings and transport details will follow.',stayTitle:'A few days in Rome',stayIntro:'Everything you need to plan your stay, all in one place.',soon:'Coming soon',stayHeading:'Somewhere to settle in',stayText:'We’re putting together a selection of hotels and places to stay. We’ll share the options, booking links and any guest rates here.',stayAside:'Haven’t booked yet?',stayAdvice:'That’s fine. When RSVPs open, you’ll be able to select “Not sure yet” and add your accommodation later.',stayLocation:'The ceremony is on the Aventine Hill and the reception is at Villa Demetra. Keep both locations in mind when planning your stay.',rsvpTitle:'Will you join us?',rsvpIntro:'We would love to have you by our side.',closed:'RSVPs are not open yet. We’ll share the details here when everything is ready.',how:'How you’ll RSVP',steps:[['Your invitation','Use your personal link or private invitation code.'],['Your plans','Let us know who’s coming and share your travel details.'],['Keep us updated','Return with the same link to view or change your response.']],questions:'What will we ask?',fields:['Who is attending from your invitation','Dietary requirements and allergies for each person','Accommodation, even if you haven’t booked yet','Transport needs, if we arrange transport'],planned:'The final questions will be available when RSVPs open.'
  }
};
for (const lang of Object.keys(copy)) copy[lang].nav.splice(1,0,dayCopy[lang].title);
const pages=['home','wedding-day','locations','accommodation','rsvp'];
let language='es';
try { const saved=localStorage.getItem('wedding-language'); if(copy[saved]) language=saved; } catch {}
function render(){
  const t=copy[language];
  const page=pages.includes(location.hash.slice(1))?location.hash.slice(1):'home';
  document.documentElement.lang=language;
  document.title=`Chiara & Yago · ${t.nav[pages.indexOf(page)]}`;
  document.querySelector('meta[name="description"]').content=`Chiara & Yago · ${t.date} · ${t.city}. ${t.nav.join(' · ')}.`;
  document.querySelectorAll('[data-text]').forEach(el=>el.textContent=t[el.dataset.text]);
  document.querySelectorAll('[data-lang]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.lang===language)));
  document.querySelector('#navigation').setAttribute('aria-label',({es:'Navegación principal',it:'Navigazione principale',en:'Main navigation'})[language]);
  document.querySelector('#navigation').innerHTML=pages.map((p,i)=>`<a href="#${p}" ${page===p?'aria-current="page"':''}>${t.nav[i]}</a>`).join('');
  const heading=(title,intro)=>`<div class="page-heading"><p class="eyebrow">${t.city} · 03.07.2027</p><h1>${title}</h1><p>${intro}</p></div>`;
  let content='';
  if(page==='home') content=`<section class="hero"><div class="hero-copy"><p class="eyebrow">${t.marry}</p><h1>Chiara <em>&</em> Yago</h1><p class="date">${t.date}</p><p class="city">${t.city}</p><p class="intro">${t.intro}</p><a class="button" href="#locations">${t.discover}</a></div><figure class="hero-photo"><img src="assets/couple.jpeg" alt="Chiara & Yago" width="3840" height="5120" fetchpriority="high"><figcaption>${t.photo}</figcaption></figure></section><section class="home-details"><article><p class="eyebrow">01 · ${t.ceremony}</p><h2>Sant’Anselmo</h2><p>Aventino · ${t.city}</p><a class="text-link" href="#locations">${t.more} →</a></article><article><p class="eyebrow">02 · ${t.reception}</p><h2>Villa Demetra</h2><p>${t.city}</p><a class="text-link" href="#locations">${t.more} →</a></article><article><p class="eyebrow">03 · ${t.weekend}</p><h2>${t.city}</h2><p>${t.stayShort}</p><a class="text-link" href="#accommodation">${t.hotels} →</a></article></section>`;
  if(page==='locations') content=`<section class="page">${heading(t.locationsTitle,t.locationsIntro)}<article class="venue"><img src="assets/church.jpg" alt="Pontificio Ateneo Sant’Anselmo" width="800" height="600"><div><p class="eyebrow">01 · ${t.ceremony}</p><h2>Pontificio Ateneo Sant’Anselmo</h2><p>${t.churchText}</p><p class="address">Piazza dei Cavalieri di Malta, 5<br>00153 Roma, Italia</p><a class="button secondary" href="https://maps.google.com/?q=Pontificio+Ateneo+Sant+Anselmo+Roma" target="_blank" rel="noopener noreferrer">${t.maps}</a></div></article><article class="venue"><img src="assets/villa.jpg" alt="Villa Demetra" loading="lazy" width="800" height="600"><div><p class="eyebrow">02 · ${t.reception}</p><h2>Villa Demetra</h2><p>${t.villaText}</p><p class="address">Via Ardeatina 1330A<br>00134 Roma, Italia</p><a class="button secondary" href="https://maps.google.com/?q=Villa+Demetra+Via+Ardeatina+1330+Roma" target="_blank" rel="noopener noreferrer">${t.maps}</a></div></article><p class="note">${t.timing}</p></section>`;
  if(page==='accommodation') content=`<section class="page">${heading(t.stayTitle,t.stayIntro)}<div class="stay"><div><span class="status">${t.soon}</span><h2>${t.stayHeading}</h2><p>${t.stayText}</p><a class="text-link" href="#locations">${t.discover} →</a></div><aside><h3>${t.stayAside}</h3><p>${t.stayAdvice}</p><p class="note">${t.stayLocation}</p></aside></div></section>`;
  if(page==='rsvp') content=`<section class="page">${heading(t.rsvpTitle,t.rsvpIntro)}<p class="notice">${t.closed}</p><div class="rsvp-card"><h2>${t.how}</h2><ol class="steps">${t.steps.map(([title,body])=>`<li><div><strong>${title}</strong><p>${body}</p></div></li>`).join('')}</ol><details><summary>${t.questions}</summary><ul>${t.fields.map(f=>`<li>${f}</li>`).join('')}</ul><p class="note">${t.planned}</p></details></div></section>`;
  if(page==='wedding-day') {
    const day=dayCopy[language];
    content=`<section class="page">${heading(day.title,day.intro)}<p class="notice">${day.notice}</p><ol class="day-timeline">${day.events.map(([title,body],i)=>`<li><span class="timeline-number" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><div><p class="timeline-time">${day.time}</p><h2>${title}</h2><p>${body}</p></div></li>`).join('')}</ol></section>`;
  }
  if(page==='rsvp') content=`<section class="page">${heading(t.rsvpTitle,t.rsvpIntro)}${rsvpView(language)}</section>`;
  document.querySelector('#main').innerHTML=content;
  if(page==='rsvp')bindRsvp();
}
document.querySelectorAll('[data-lang]').forEach(button=>button.addEventListener('click',()=>{language=button.dataset.lang;try{localStorage.setItem('wedding-language',language);}catch{}render();}));
window.addEventListener('hashchange',()=>{render();document.querySelector('#main').focus({preventScroll:true});window.scrollTo(0,0);});
render();
