import {today,summary,events,effectiveStatus,remainingMonth,paymentSymbol,monthCompleted,validateItems} from './finance-items.mjs?v=items-20260919';
import {lineTotals,cents} from './finance-model.mjs';
const $=id=>document.getElementById(id),form=$('supplier-form'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'}).format(n/100),decimal=n=>(n/100).toFixed(2);
let upcomingPage=0;
const upcomingPageSize=5;
let key='';
let state,editing,dirty=false,saving=false,month=today().slice(0,7),selected=today();
async function api(route,body={}){const response=await fetch(window.RSVP_API_URL.replace(/\/$/,'')+'/admin/finance/'+route,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+key},body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error(response.status===401?'Administrator key not accepted.':response.status===409?'This record changed. Copy your edits, close the form, and refresh before trying again.':response.status===400?'Check the required fields, dates, amounts and document link.':'Unable to reach finance storage. Please try again.');return response.json();}
async function load(){state=await api('list');render();}
const breakdown=(net,tax)=>`<div class="price-parts"><span>Net <b>${money(net)}</b></span><span>IVA only <b>${money(tax)}</b></span></div>`;
function render(){
 const accepted=state.records.filter(r=>effectiveStatus(r)!=='quote');
 const sum=(records,key)=>records.reduce((n,r)=>n+summary(r)[key],0);
 $('stats').innerHTML=[['Booked total',sum(accepted,'total'),sum(accepted,'net'),sum(accepted,'tax')],['Paid so far',sum(state.records,'paid'),sum(state.records,'netPaid'),sum(state.records,'taxPaid')],['Still to pay',sum(accepted,'balance'),sum(accepted,'netBalance'),sum(accepted,'taxBalance')]].map(([label,total,net,tax])=>`<div class="stat"><h2>${label}</h2><small>Including IVA</small><strong>${money(total)}</strong>${breakdown(net,tax)}</div>`).join('');
 const q=$('search').value.toLowerCase();
 $('suppliers').innerHTML=state.records.filter(r=>[r.supplier,r.title].join(' ').toLowerCase().includes(q)).map(r=>{const t=summary(r),status=effectiveStatus(r);return `<article class="supplier ${status}"><div class="identity"><h3>${esc(r.supplier)}</h3><span class="status-badge">${status==='completed'?'✓ Completed · Fully paid':status==='quote'?'Quote · Provisional':'Booked'}</span><p>${esc(r.title)} · ${r.items.length} item${r.items.length===1?'':'s'}</p></div><div class="supplier-prices"><div><small>${status==='quote'?'Provisional total':'Total'} including IVA</small><strong>${money(t.total)}</strong>${breakdown(t.net,t.tax)}</div><div><small>Paid including IVA</small><strong>${money(t.paid)}</strong>${breakdown(t.netPaid,t.taxPaid)}</div><div><small>${status==='quote'?'Provisional remaining':'Remaining'} including IVA</small><strong>${money(t.balance)}</strong>${breakdown(t.netBalance,t.taxBalance)}</div></div><button data-edit="${esc(r.id)}" class="secondary">Open supplier</button></article>`;}).join('')||'<p>No matching suppliers.</p>';
 $('suppliers').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>open(state.records.find(r=>r.id===b.dataset.edit)));
 renderUpcoming();calendar();
}
function renderUpcoming(){
 const due=events(state.records).filter(e=>e.kind==='deadline'),pages=Math.ceil(due.length/upcomingPageSize);
 upcomingPage=Math.max(0,Math.min(upcomingPage,pages-1));
 const start=upcomingPage*upcomingPageSize,visible=due.slice(start,start+upcomingPageSize);
 $('upcoming').innerHTML=visible.map(e=>`<article class="due-row compact-due ${e.date<today()?'red':''}"><div class="due-date"><span class="payment-symbol" role="img" aria-label="${e.rate>=800?'Card: IVA at least 8%':'Dollar: IVA below 8%'}" title="IVA ${decimal(e.rate)}%">${e.rate>=800?'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="2" y="4" width="20" height="16" rx="3"/><path d="M2 9h20M6 15h4"/></svg>':paymentSymbol(e.rate)}</span><time datetime="${esc(e.date)}">${esc(e.date)}</time>${e.date<today()?'<span class="due-overdue">Overdue</span>':''}</div><div class="due-description"><strong>${esc(e.supplier)}</strong><span>${esc(e.label)}</span></div><div class="due-price"><strong>${money(e.amount)} <span>incl. IVA</span></strong><span>Net ${money(e.net)} · IVA ${money(e.tax)}</span></div></article>`).join('')||'<p>No unpaid deadlines on booked services.</p>';
 $('upcoming-pagination').hidden=pages<=1;
 $('upcoming-page').textContent=due.length?`${start+1}–${Math.min(start+upcomingPageSize,due.length)} of ${due.length}`:'';
 $('upcoming-prev').disabled=upcomingPage===0;
 $('upcoming-next').disabled=upcomingPage>=pages-1;
}
$('upcoming-prev').onclick=()=>{upcomingPage--;renderUpcoming();};
$('upcoming-next').onclick=()=>{upcomingPage++;renderUpcoming();};

function calendar(){const remaining=remainingMonth(state.records,month),complete=monthCompleted(state.records,month);$('month-remaining').classList.toggle('is-complete',complete);$('month-remaining').innerHTML=`<div class="month-summary-head"><h3>${new Date(Number(month.slice(0,4)),Number(month.slice(5))-1,1).toLocaleDateString('en-GB',{month:'long',year:'numeric'})}</h3><span>${complete?'✓ All paid':remaining.count?remaining.count+' unpaid':'No payments due'}</span></div><div class="month-summary-values"><span>Remaining incl. IVA <strong>${money(remaining.total)}</strong></span><span>Net <b>${money(remaining.net)}</b></span><span>IVA only <b>${money(remaining.tax)}</b></span></div>`;const all=events(state.records),[y,m]=month.split('-').map(Number),first=new Date(y,m-1,1);$('month').textContent=first.toLocaleDateString('en-GB',{month:'long',year:'numeric'});let html=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<span>${d}</span>`).join('')+'<span></span>'.repeat((first.getDay()+6)%7);for(let d=1;d<=new Date(y,m,0).getDate();d++){const date=month+'-'+String(d).padStart(2,'0'),items=all.filter(e=>e.date===date),deadline=items.some(e=>e.kind==='deadline'),paid=items.some(e=>e.kind==='paid');html+=`<button type="button" data-date="${date}" class="${deadline?'deadline ':''}${paid?'paid ':''}${deadline&&paid?'both':''}" aria-label="${date}${deadline?', deadline':''}${paid?', paid':''}" aria-pressed="${selected===date}" ${date===today()?'aria-current="date"':''}>${d}</button>`;}$('days').innerHTML=html;$('days').querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{selected=b.dataset.date;calendar();$('days').querySelector(`[data-date="${selected}"]`).focus();});$('day-events').innerHTML=`<p><strong>${selected}</strong></p>`+(all.filter(e=>e.date===selected).map(e=>`<p class="${e.kind==='paid'?'green':'red'}">${e.kind==='paid'?'Paid':'Deadline'} · ${esc(e.supplier)} · ${esc(e.label)} · ${money(e.amount)} including IVA<br>Net ${money(e.net)} · IVA only ${money(e.tax)}</p>`).join('')||'<p>No payments or deadlines on this day.</p>');}
function move(delta){const [y,m]=month.split('-').map(Number),d=new Date(y,m-1+delta,1);month=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;selected=month+'-01';calendar();}
$('prev').onclick=()=>move(-1);$('next').onclick=()=>move(1);$('today').onclick=()=>{selected=today();month=selected.slice(0,7);calendar();};$('search').oninput=()=>state&&render();
function newItem(){return {id:crypto.randomUUID(),description:'',amount:0,basis:'gross',rate:0,taxNote:'',deadline:'',paid:false,paidDate:''};}
function open(r){editing=r?structuredClone(r):{id:crypto.randomUUID(),version:0,schemaVersion:2,currency:'EUR',reference:'',quoteDate:'',document:'',supplier:'',title:'',category:'Other',status:'contracted',notes:'',items:[newItem()]};for(const name of ['supplier','title','status','notes','category','reference','quoteDate','document'])form.elements[name].value=editing[name]??'';form.elements.status.value=effectiveStatus(editing)==='quote'?'quote':'contracted';$('editor-title').textContent=r?r.supplier:'New supplier';$('error').textContent='';renderItems();$('delete-supplier').hidden=!r;dirty=false;$('editor').showModal();}
function renderItems(){const field=(label,name,value,type='text',extra='')=>`<label>${label}<input data-field="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;$('items').innerHTML=editing.items.map((i,n)=>`<section class="item" data-item="${n}"><div class="item-fields">${field('Description','description',i.description,'text','required maxlength="200"')}${field('Item amount (€)','amount',decimal(i.amount),'number','required min="0" max="99999999.99" step="0.01"')}<label>Amount is<select data-field="basis"><option value="gross" ${i.basis==='gross'?'selected':''}>After IVA</option><option value="net" ${i.basis==='net'?'selected':''}>Before IVA</option></select></label>${field('IVA rate (%)','rate',decimal(i.rate),'number','required min="0" max="100" step="0.01"')}${field('Deadline','deadline',i.deadline,'date')}</div><div class="item-bottom"><label class="check"><input data-field="paid" type="checkbox" ${i.paid?'checked':''}>Paid</label><label class="paid-date" ${!i.paid?'hidden':''}>Date paid<input data-field="paidDate" type="date" value="${esc(i.paidDate)}" ${i.paid?'required':''}></label><span class="item-amount"></span><button type="button" class="secondary remove">Remove</button></div></section>`).join('');$('items').querySelectorAll('[data-item]').forEach(el=>{const i=editing.items[Number(el.dataset.item)];el.querySelector('.remove')?.addEventListener('click',()=>{try{readItems();}catch{$('error').textContent='Check item amounts before removing an item.';return;}editing.items.splice(Number(el.dataset.item),1);dirty=true;renderItems();});});updateTotals();}
function readItems(){for(const el of $('items').children){const item=editing.items[Number(el.dataset.item)];for(const input of el.querySelectorAll('[data-field]')){const k=input.dataset.field;item[k]=k==='paid'?input.checked:['amount','rate'].includes(k)?cents(input.value):input.value;}}}
function updateTotals(){try{readItems();const t=summary(editing);$('completion-note').textContent=form.elements.status.value==='quote'?'Provisional quote · excluded from booked totals.':effectiveStatus({...editing,status:'contracted'})==='completed'?'✓ Completed · All items are paid.':'Completion is automatic when every item is marked paid.';$('item-totals').innerHTML=`<div class="net-total">Before IVA<strong>${money(t.net)}</strong></div><div class="iva-total">IVA<strong>${money(t.tax)}</strong></div><div class="gross-total">Including IVA<strong>${money(t.total)}</strong></div><small>Paid including IVA ${money(t.paid)} · Net ${money(t.netPaid)} · IVA ${money(t.taxPaid)}<br>Remaining including IVA ${money(t.balance)} · Net ${money(t.netBalance)} · IVA ${money(t.taxBalance)}</small>`;$('items').querySelectorAll('[data-item]').forEach(el=>{const i=editing.items[Number(el.dataset.item)],t=lineTotals(i);el.classList.toggle('item-paid',i.paid);el.querySelector('.item-amount').innerHTML=`${money(t.total)} including IVA${breakdown(t.net,t.tax)}`;});}catch{$('item-totals').textContent='Enter valid amounts to see the totals.';}}
$('items').addEventListener('input',e=>{dirty=true;if(e.target.dataset.field==='paid'){const el=e.target.closest('.item'),paidDate=el.querySelector('[data-field="paidDate"]');el.querySelector('.paid-date').hidden=!e.target.checked;paidDate.required=e.target.checked;if(e.target.checked&&!paidDate.value)paidDate.value=today();}updateTotals();});
form.addEventListener('input',()=>{dirty=true;updateTotals();});
$('add-item').onclick=()=>{try{readItems();editing.items.push(newItem());dirty=true;renderItems();$('items').lastElementChild.querySelector('input').focus();}catch{$('error').textContent='Complete the current item amounts before adding another.';}};
function close(){if(saving)return;if(dirty&&!confirm('Discard your unsaved changes?'))return;$('editor').close();dirty=false;}
$('close').onclick=close;$('editor').addEventListener('cancel',e=>{e.preventDefault();close();});$('add').onclick=()=>state&&open();
function lockForm(locked){saving=locked;form.querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=locked);}
form.onsubmit=async e=>{e.preventDefault();if(saving)return;try{readItems();for(const n of ['supplier','title','status','notes','category','reference','quoteDate','document'])editing[n]=form.elements[n].value;const record=validateItems({...editing,currency:'EUR',schemaVersion:2});lockForm(true);const result=await api('save',{id:editing.id,version:editing.version||0,record});const saved={...record,id:editing.id,version:result.version};const index=state.records.findIndex(r=>r.id===saved.id);if(index<0)state.records.unshift(saved);else state.records[index]=saved;dirty=false;$('editor').close();render();$('status').textContent='Supplier saved.';}catch(e){$('error').textContent=e.message==='INVALID'?'Check the required fields, dates, amounts and document link.':e.message;}finally{lockForm(false);}};
$('delete-supplier').onclick=async()=>{if(saving||!editing?.version)return;if(!confirm(`Delete ${editing.supplier} — ${editing.title}? This removes this supplier record and its items permanently.`))return;try{lockForm(true);await api('delete',{id:editing.id,version:editing.version});state.records=state.records.filter(r=>r.id!==editing.id);dirty=false;$('editor').close();render();$('status').textContent='Supplier deleted.';}catch(e){$('error').textContent=e.message;}finally{lockForm(false);}};
$('login-form').onsubmit=async e=>{e.preventDefault();key=$('key').value;$('login-status').textContent='Loading…';const button=$('login-form').querySelector('button');button.disabled=true;try{await load();$('key').value='';$('login').hidden=true;$('dashboard').hidden=false;$('login-status').textContent='';}catch(e){key='';$('login-status').textContent=e.message;}finally{button.disabled=false;}};
$('refresh').onclick=async()=>{try{await load();$('status').textContent='Updated.';}catch(e){$('status').textContent=e.message;}};
$('logout').onclick=()=>{if(saving)return;if(dirty&&!confirm('Discard unsaved changes and sign out?'))return;key='';state=null;editing=null;dirty=false;upcomingPage=0;selected=today();month=selected.slice(0,7);form.reset();$('search').value='';for(const id of ['suppliers','stats','upcoming','upcoming-page','days','day-events','month-remaining','items','item-totals','error','status','completion-note','editor-title'])$(id).innerHTML='';$('editor').close();$('dashboard').hidden=true;$('login').hidden=false;};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
